version: '1'
services:
  web:
    image: web:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    expose:
      - 8000
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && chmod +x /app/entrypoint.sh && sh /app/entrypoint.sh"
    depends_on:
      - db
  
  bd:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc#123$
      POSTGRES_DB: bookstore
    ports:
      -'5432:5432'
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    